# Generated by Django 3.2.4 on 2021-07-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakaocmd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bschedule',
            name='bfive',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='bschedule',
            name='bfour',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='bschedule',
            name='bsisdeleted',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='bschedule',
            name='bsix',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='bschedule',
            name='bthree',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='bschedule',
            name='btwo',
            field=models.CharField(default='', max_length=12),
        ),
    ]
