# Generated by Django 3.2.4 on 2021-07-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kakaocmd', '0003_auto_20210702_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bschedule',
            name='bdate',
            field=models.CharField(max_length=10),
        ),
    ]
